

export const platforms = {
    Instagram: '/images/icon-instagram.svg',
    Tiktok: '/images/icon-tiktok.svg',
    Snapchat: '/images/icon-snapchat.svg',
    Whatsapp: '/images/icon-whatsapp.svg',
    Telegram: '/images/icon-telegram.svg',
    CodePen: '/images/icon-codepen.svg',
    Codewars: '/images/icon-codewars.svg',
    DevTo: '/images/icon-devto.svg',
    Facebook: '/images/icon-facebook.svg',
    freeCodeCamo: '/images/icon-freecodecamp.svg',
    FrontendMentor: '/images/icon-frontend-mentor.svg',
    GitHub: '/images/icon-github.svg',
    GitLab: '/images/icon-gitlab.svg',
    HashNode: '/images/icon-hashnode.svg',
    LinkedIn: '/images/icon-linkedin.svg',
    StackOverflow: '/images/icon-stack-overflow.svg',
    Twitch: '/images/icon-twitch.svg',
    Twitter: '/images/icon-twitter.svg',
    YouTube: '/images/icon-youtube.svg',
  }


  export const colors = {
    Instagram: '#8A1A50',
    Tiktok: '#1A1A1A',
    Snapchat: '#EC7100',
    Whatsapp: '#005208',
    Telegram: '#43B7E9',
    CodePen: '#D9D9D9',
    Codewars: '#8A1A50',
    DevTo: '#333333',
    Facebook: '#2442AC',
    freeCodeCamo: '#302267',
    FrontendMentor: '#D9D9D9',
    GitHub: '#1A1A1A',
    GitLab: '#EB4925',
    HashNode: '#0330D1',
    LinkedIn: '#2D68FF',
    StackOverflow: '#EC7100',
    Twitch: '#EE3FC8',
    Twitter: '#43B7E9',
    YouTube: '#EE3939',
  }
